version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.11.0
    steps:
      - checkout
      - run:
         name: install numpy
         command: |
           pip install numpy
      - run:
         name: write to file
         command: |
           python main.py
