version: 2.1

jobs:
  run-code:
    steps:
      - checkout
      - run:
         name: install clang
         command: |
           sudo apt install clang
      - run:
         name: run C file
         command: |
           clang main.c
           ./a.out
