version: 2.1

jobs:
  # Job one with a unique name
  show_files:
    docker:
      - image: alpine:3.15
    steps:
      - checkout
      - run: 
         name: show all files in current folder
         command: |
           ls -a
  greet_usr:
          docker:
            - image: cimg/base:2021.04
          steps:
            - run:
               name: Greet user
               command: |
                 echo "GOOD MORNING JOHN"
  using_node:
    docker:
      - image: cimg/node:17.2
    steps:
      - run:
         name: Show node version
         command: |
           node -v

workflows:
  example_workflows:
    jobs:
      - show_files:
        type: approval
      - greet_usr:
        requires:
          - show-files
      - using_node:
        type: approval
        requires:
          - show_files
          - greet_usr

