version: 2.1

jobs:
  # Job one with a unique name
  show_files:
    docker:
      - image: alpine:3.15
    steps:
      - checkout
      - run: 
        name: show all files in current folder
        command: |
          ls -a
          echo "___My files___"

