version: 2.1

jobs:
  # Job one with a unique name
  show_files:
    docker:
      - image: alpine:3.15
    steps:
      - checkout
      - run: 
         name: show all files in current folder
         command: |
           ls -a
  greet_usr:
          docker:
            - image: cimg/base:2021.04
          steps:
            - run: echo "GOOD MORNING JOHN"
 workflows:
   example_workflows:
     jobs:
       - show_files
       - greet_usr
