name: CI/CD pipeline
on:
  push:
    branches: main
jobs:
  Mywork-flow:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v3
     - run: sudo apt install clang
     - run: clang main.c
      
