name: Learning linux

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: First job
      run: ls -a
      # run: chmod +x HelloLinux.sh && ./HelloLinux.sh
