name: CI/CD pipeline
on:
  push:
    branches: main
jobs:
  Mywork-flow:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v3
     - run: curl https://github.com/google/bundletool/releases/download/1.13.1/bundletool-all-1.13.1.jar
     - run: ls
     - uses: actions/upload-artifact@v3
       with:
         name: MainC
         path: ./main.c

     - run: mkdir downloads
     - uses: actions/download-artifact@v3
       with:
         name: MainC
         path: ./downloads

     - run: ls -R
