name: CI/CD pipeline
on:
  push:
    branches: main
jobs:
  Mywork-flow:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v3
     - uses: actions/upload-artifact@v3
       with:
         name: MainC
         path: ./main.c

     - run: mkdir downloads
     - uses: actions/download-artifact@v3
       with:
         name: MainC
         path: ./downloads

     - run: ls -R
