name: Build youtube video downloader
on:
  push:
    branches: [ "main" ]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: 3.10
    - run: chmod +x HelloLinux.sh
    - run: ./HelloLinux.sh